PM_combine_/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accountapp.urls')),
    path('location/', include('locationapp.urls')),
    path('usage/', include('usageapp.urls')),
]

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import create, login, logout

app_name = "accountapp"

urlpatterns = [
    path('create/', create, name='create'),
    path('', login, name='login'),
    path('logout/', logout, name='logout'),
]

usageapp/urls.py
from django.urls import path

from usageapp.views import data_usage, chart

app_name = 'usageapp'

urlpatterns = [
    path('data_usage/', data_usage, name='data_usage'),
    path('json_chart/', chart, name='chart')
]

accountapp/models.py
from django.db import models

# Create your models here.

class NEWMODEL(models.Model):
    text = models.CharField(max_length=255, null=False)

accountapp/views.py
from django.contrib import auth, messages
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

# Create your views here.

# 회원가입
def create(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(
                                            username=request.POST['username'],
                                            password=request.POST['password1'],
                                            email=request.POST['email'],)
            auth.login(request, user)
            print('회원가입에 성공하였습니다.')
            return redirect('accountapp:login')
        else:
            print('회원가입에 실패하였습니다.')
            return render(request, 'accountapp/create.html')
    return render(request, 'accountapp/create.html')

# 메인
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            print('로그인에 성공하였습니다.')
            return redirect('locationapp:main') # 로그인이 성공하였을 경우 PM 위치로 연결
        else:
            print('로그인에 실패하였습니다.')
            return render(request, 'accountapp/main.html', {'error': 'username or password is incorrect.'})
    else:
        return render(request, 'accountapp/main.html')

# 로그아웃
@login_required
def logout(request):
    auth.logout(request)
    print('로그아웃 되었습니다.')
    return redirect('accountapp:login')

accountapp/templates/accountapp/create.html
{% extends 'main_base.html' %}

{% block content %}
    <section class="login-form">
        <h1>회원가입</h1>
        <form method="post">
            {% csrf_token %}
            <div class="int-area">
                <input type="text" name="username" id="username"
                       autocomplete="off" required>
                <label for="username">아이디</label>
            </div>
            <div class="int-area">
                <input type="password" name="password1" id="password1"
                       autocomplete="off" required>
                <label for="password1">비밀번호</label>
            </div>
            <div class="int-area">
                <input type="password" name="password2" id="password2"
                       autocomplete="off" required>
                <label for="password2">비밀번호 확인</label>
            </div>
            <div class="int-area">
                <input type="email" name="email" id="email"
                       autocomplete="off" required>
                <label for="email">이메일</label>
            </div>
            <div class="btn-area">
                <button type="submit">완료</button>
            </div>
        </form>
    </section>
{% endblock %}

accountapp/templates/accountapp/main.html
{% extends 'main_base.html' %}

{% block content %}
    <section class="login-form">
        <h1>
            <a href="{% url 'accountapp:login' %}">
                <img src="http://www.eunsung.net/img/main/logo-b.png" alt="main">
            </a>
        </h1>
        <form method="post">
            {% csrf_token %}
            <div class="int-area">
                <input type="text" name="username" id="username"
                       autocomplete="off" required>
                <label for="username">아이디</label>
            </div>
            <div class="int-area">
                <input type="password" name="password" id="password"
                       autocomplete="off" required>
                <label for="password">비밀번호</label>
            </div>
                <div class="btn-area">
                    <button type="submit" value="Login">로그인</button>
                </div>
        </form>
            <a href="{% url 'accountapp:create' %}">
                <div class="btn-area">
                    <button type="submit">회원가입</button>
                </div>
            </a>
    </section>
{% endblock %}