PM_combine_/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accountapp.urls')),
    path('location/', include('locationapp.urls')),
    path('usage/', include('usageapp.urls')),
]

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import create, login, logout

app_name = "accountapp"

urlpatterns = [
    path('create/', create, name='create'),
    path('', login, name='login'),
    path('logout/', logout, name='logout'),
]

locationapp/urls.py
from django.urls import path

from locationapp.views import main, showmap

app_name= 'locationapp'

urlpatterns = [
    path('main', main, name='main'),      #showmap,/<int:pk>
    path('json_data/', showmap, name='showmap')
]

usageapp/urls.py
from django.urls import path

from usageapp.views import data_usage, chart

app_name = 'usageapp'

urlpatterns = [
    path('data_usage/', data_usage, name='data_usage'),
    path('json_chart/', chart, name='chart')
]

locationapp/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AccountappNewmodel(models.Model):
    id = models.BigAutoField(primary_key=True)
    text = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'accountapp_newmodel'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class NewTable(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'new_table'


class Parking(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=45, blank=True, null=True)
    address = models.CharField(max_length=45, blank=True, null=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    photo = models.CharField(max_length=75, blank=True, null=True)
    gcooter = models.IntegerField(blank=True, null=True)
    deer = models.IntegerField(blank=True, null=True)
    beam = models.IntegerField(blank=True, null=True)
    talang = models.IntegerField(blank=True, null=True)
    kickboard = models.IntegerField(blank=True, null=True)
    bicycle = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'parking'


class Pm(models.Model):
    id = models.CharField(primary_key=True, max_length=20)
    name = models.CharField(max_length=45, blank=True, null=True)
    type = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'pm'

locationapp/views.py
import self as self
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
import  json
# Create your views here.
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
from rest_framework.response import Response

from locationapp.models import Parking
from locationapp.serializers import pm_combine


@login_required
def main(request):
    return render(request, 'locationapp/main.html')

@api_view(["GET"])
def showmap(request):       #,pk
    location = Parking.objects.all()

    temp = pm_combine(location, many=True)

    return Response(temp.data)

locationapp/templates/locationapp/main.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>parking information</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="http://www.eunsung.net/img/main/logo-b.png" alt="main">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="{% url 'locationapp:main' %}">Location</a>
                    <a class="nav-link" href="{% url 'usageapp:data_usage' %}">Usage</a>
                    <a class="nav-link" href="{% url 'accountapp:logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </nav>
    <style>
        b{
            color : brown;
        }
    </style>
</head>
<body>
<div id="map" style="width:100%;height:100vh;"></div>
<script src="https://code.jquery.com/jquery-latest.js"></script>
<script src="https://dapi.kakao.com/v2/maps/sdk.js?appkey=95d96928be2258e3a2ad2028960c5c28&libraries=clusterer
"></script>
<script>
    var mapContainer = document.getElementById('map'), // 지도를 표시할 div
        mapOption = {
            center: new kakao.maps.LatLng(35.1545732, 126.9235121), // 지도의 중심좌표
            level: 4, // 지도의 확대 레벨
            mapTypeId: kakao.maps.MapTypeId.ROADMAP // 지도종류
        };
    // 지도를 생성한다
    var map = new kakao.maps.Map(mapContainer, mapOption);
    var clusterer = new kakao.maps.MarkerClusterer({
        map: map, // 마커들을 클러스터로 관리하고 표시할 지도 객체
        averageCenter: true, // 클러스터에 포함된 마커들의 평균 위치를 클러스터 마커 위치로 설정
        minLevel: 10 // 클러스터 할 최소 지도 레벨
    });
    var markers = [];

    $.ajax({
        url : "http://127.0.0.1:8000/location/json_data/",
        dataType: "json"
    }).done(function (data) {
        console.log(data);

        for (var  idx = 0; idx < data.length; idx++) {
            {#console.log("마커찍을 좌표:",  data[idx].latitude,data[idx].longitude)}#}
            var markerPosition = new kakao.maps.LatLng(data[idx].latitude, data[idx].longitude);

            var marker = new kakao.maps.Marker({
                position:  new kakao.maps.LatLng(data[idx].latitude, data[idx].longitude),
                map:map
            });
            let able=data[idx].talang+data[idx].beam+data[idx].deer+data[idx].gcooter
            let iwContent = '<div  style="padding:5px;width:600px; height: auto; text-align: left; background-color: antiquewhite; border: 1px solid ;border-top:none;">'+'<b>주소 :</b> '+data[idx].address+'</br>'+'<b>가용가능한 pm : </b>'+able+'</br>'+
                '<b>gcooter :</b>'+data[idx].gcooter+'</br>'+'<b>talang :</b>'+data[idx].talang+'</br>'+'<b>beam :</b>'+data[idx].beam+'</br>'+'<b>deer :</b>'+data[idx].deer
                '</div>';




            var infowindow = new kakao.maps.InfoWindow({
                content : iwContent
            });

            kakao.maps.event.addListener(marker, 'mouseover', makeOverListener(map, marker, infowindow));
            kakao.maps.event.addListener(marker, 'mouseout', makeOutListener(infowindow));
            markers.push(marker);




        }
        clusterer.addMarkers(markers);
        function makeOverListener(map, marker, infowindow) {
            return function() {
                infowindow.open(map, marker);
            };
        }

        function makeOutListener(infowindow) {
            return function() {
                infowindow.close();
            };
        }});
</script>
</body>
</html>